- type: entity
  name: CrystalThistle
  parent: FoodProduceBase
  id: FoodCrystalThistle
  description: A variant of galaxythistle that has sprouted sharp quartz shards.
  components:
  - type: FlavorProfile
    flavors:
    - sharp
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 25
        reagents:
        - ReagentId: Quartzite
          Quantity: 10
        - ReagentId: Ethyloxyephedrine
          Quantity: 15
  - type: Sprite
    sprite: DeltaV/Objects/Specific/Hydroponics/Crystal_Thistle.rsi
  - type: Produce
    seedId: CrystalThistle
  - type: Extractable
    grindableSolutionName: food
  - type: FoodSequenceElement
    entries:
      Burger: CrystalThistle
      Taco: CrystalThistle
      Skewer: CrystalThistle

- type: foodSequenceElement
  id: CrystalThistle
  name: food-sequence-content-crystal-thistle
  sprites:
  - sprite: DeltaV/Objects/Specific/Hydroponics/Crystal_Thistle.rsi
    state: produce

- type: entity
  name: Ghost Pepper
  parent: FoodProduceBase
  id: FoodGhostPepper
  description: So hot, you'll have one foot in the grave.
  components:
  - type: FlavorProfile
    flavors:
    - spicy
    - sweet
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 39
        reagents:
        - ReagentId: Nutriment
          Quantity: 6
        - ReagentId: CapsaicinOil
          Quantity: 15
        - ReagentId: Vitamin
          Quantity: 6
        - ReagentId: Thermite
          Quantity: 10
  - type: TileFrictionModifier
    modifier: 0.05
  - type: Sprite
    sprite: DeltaV/Objects/Specific/Hydroponics/Ghost_Pepper.rsi
  - type: Produce
    seedId: GhostPepper
  - type: Tag
    tags:
    - Vegetable
  - type: FoodSequenceElement
    entries:
      Burger: GhostPepper
      Taco: GhostPepper
      Skewer: GhostPepper

- type: foodSequenceElement
  id: GhostPepper
  name: food-sequence-content-ghost-pepper
  sprites:
  - sprite: DeltaV/Objects/Specific/Hydroponics/Ghost_Pepper.rsi
    state: produce
  tags:
  - Vegetable

- type: entity
  name: Cosmic Revenant
  parent: FoodProduceBase
  id: FoodCosmicRevenant
  description: Is this even a pepper? Looks... Haunted.
  components:
  - type: FlavorProfile
    flavors:
    - spicy
    - spooky
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 41
        reagents:
        - ReagentId: Nutriment
          Quantity: 8
        - ReagentId: CapsaicinOil
          Quantity: 20
        - ReagentId: Vitamin
          Quantity: 8
        - ReagentId: Ectoplasm
          Quantity: 5
  - type: TileFrictionModifier
    modifier: 0.0001
  - type: Sprite
    sprite: DeltaV/Objects/Specific/Hydroponics/Cosmic_Revenant.rsi
  - type: Produce
    seedId: CosmicRevenant
  - type: Tag
    tags:
    - Vegetable
  - type: FoodSequenceElement
    entries:
      Burger: CosmicRevenant
      Taco: CosmicRevenant
      Skewer: CosmicRevenant

- type: foodSequenceElement
  id: CosmicRevenant
  name: food-sequence-content-revenant
  sprites:
  - sprite: DeltaV/Objects/Specific/Hydroponics/Cosmic_Revenant.rsi
    state: produce
  tags:
  - Vegetable

- type: entity
  name: papercane roll
  description: Why do we even need to grow paper?
  id: Papercane
  parent: ProduceBase
  components:
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/papercane.rsi
  - type: SolutionContainerManager
  - type: Produce
    seedId: papercane
  - type: Log
    spawnedPrototype: SheetPaper1
    spawnCount: 2

- type: entity
  name: extradimensional orange
  parent: FoodProduceBase
  id: FoodExtradimensionalOrange
  description: You can hardly wrap your head around this thing.
  components:
  - type: FlavorProfile
    flavors:
      - truenature
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 14
        reagents:
        - ReagentId: Haloperidol
          Quantity: 5
        - ReagentId: Nutriment
          Quantity: 5
        - ReagentId: Vitamin
          Quantity: 4
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/extradimensional_orange.rsi
    scale: 0.5,0.5
  - type: Produce
    seedId: extradimensionalOrange
  - type: PotencyVisuals
    minimumScale: 0.5 # reduce this in size because the sprite is way too big
    maximumScale: 1
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceOrange
        Quantity: 10
  - type: Tag
    tags:
    - Fruit
  - type: FoodSequenceElement
    entries:
      Burger: ExtradimensionalOrangeBurger
      Taco: ExtradimensionalOrange

- type: entity
  name: golden apple
  parent: FoodProduceBase
  id: FoodGoldenApple
  description: It should be shaped like a cube, shouldn't it?
  components:
  - type: FlavorProfile
    flavors:
      - apple
      - metallic
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 30
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: Vitamin
          Quantity: 4
        - ReagentId: DoctorsDelight
          Quantity: 13
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/golden_apple.rsi
  - type: Produce
    seedId: goldenApple
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceApple
        Quantity: 10
      - ReagentId: Gold
        Quantity: 10
  - type: Tag
    tags:
    - Fruit
  - type: FoodSequenceElement
    entries:
      Burger: GoldenApple
      Taco: GoldenApple

- type: entity
  name: glasstle
  parent: FoodProduceBase
  id: FoodGlasstle
  description: A fragile crystal plant with lot of spiky thorns.
  components:
  - type: Item
    size: Small
    sprite: Objects/Specific/Hydroponics/glasstle.rsi
    heldPrefix: produce
  - type: FlavorProfile
    flavors:
      - sharp
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 15
        reagents:
        - ReagentId: Razorium
          Quantity: 15
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/glasstle.rsi
  - type: Produce
    seedId: glasstle
  - type: Extractable
    grindableSolutionName: food
  - type: Damageable
    damageContainer: Inorganic
  - type: ToolRefinable
    refineResult:
    - id: SheetGlass1
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 10
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: GlassBreak
          params:
            volume: -4
      - !type:SpawnEntitiesBehavior
        spawn:
          ShardGlass:
            min: 1
            max: 1
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: DamageOnHit
    damage:
      types:
        Blunt: 10
  - type: MeleeWeapon
    wideAnimationRotation: 60
    damage:
      types:
        Slash: 15
    soundHit:
        path: /Audio/Weapons/bladeslice.ogg
  - type: Tag
    tags:
    - Galaxythistle
  - type: FoodSequenceElement
    entries:
      Taco: Glasstle
      Burger: GlasstleBurger

- type: entity
  name: capfruit
  parent: FoodProduceBase
  id: FoodRealCapfruit
  description: A soft but smooth gun-shaped fruit.
  components:
  - type: FlavorProfile
    flavors:
      - plastic
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Nutriment
          Quantity: 5
        - ReagentId: Sulfur
          Quantity: 5
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/capfruit.rsi
  - type: Produce
    seedId: realCapfruit
  - type: Food
    trash:
    - RevolverCapGun
  - type: Tag
    tags:
    - Fruit
  - type: FoodSequenceElement
    entries:
      Taco: Capfruit
      Burger: CapfruitBurger

- type: entity
  name: capfruit
  parent: FoodRealCapfruit
  id: FoodFakeCapfruit
  suffix: Fake
  components:
  - type: Produce
    seedId: fakeCapfruit
  - type: Food
    trash:
    - RevolverCapGunFake

- type: entity
  name: holymelon
  parent: [FoodProduceBase, ItemHeftyBase]
  id: FoodHolymelon
  description: The water within this melon has been blessed by some deity that's particularly fond of watermelon.
  components:
  - type: Item
    size: Small
  - type: FlavorProfile
    flavors:
      - holy
      - watermelon
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 25
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: Vitamin
          Quantity: 5
        - ReagentId: HolyWater # DeltaV - use our holy water
          Quantity: 10
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/holymelon.rsi
  - type: Produce
    seedId: watermelon
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: Wine
        Quantity: 20
  - type: Damageable
    damageContainer: Biological
  - type: DamageOnHighSpeedImpact
    minimumSpeed: 0.1
    damage:
      types:
        Blunt: 1
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 1
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: desecration
      - !type:SpillBehavior
        solution: food
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: SliceableFood
    count: 5
    slice: FoodHolymelonSlice
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: holymelon slice
  parent: ProduceSliceBase
  id: FoodHolymelonSlice
  description: Juicy golden and red slice.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - holy
      - watermelon
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/holymelon.rsi
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: Vitamin
          Quantity: 1
        - ReagentId: HolyWater # DeltaV - use our holy water
          Quantity: 2
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: Wine
        Quantity: 4
  - type: Tag
    tags:
    - Fruit
    - Slice
  - type: FoodSequenceElement
    entries:
      Burger: HolymelonSliceBurger
      Taco: HolymelonSlice
      Skewer: HolymelonSliceSkewer

- type: entity
  parent: FoodProduceBase
  id: FoodWorldPeas
  name: cluster of world peas
  description: It's rumored to bring peace to any who consume it.
  components:
  - type: FlavorProfile
    flavors:
      - numbingtranquility
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 8
        reagents:
        - ReagentId: Happiness
          Quantity: 3
        - ReagentId: Nutriment
          Quantity: 3
        - ReagentId: Pax
          Quantity: 2
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/world_pea.rsi
  - type: Produce
    seedId: worldPea
  - type: Tag
    tags:
    - Vegetable
  - type: FoodSequenceElement
    entries:
      Taco: WorldPea
      Burger: WorldPeaBurger

- type: entity
  name: blue pumpkin
  parent: FoodProduceBase
  id: FoodBluePumpkin
  description: A large, blue... berry. Seriously.
  components:
  - type: Item
    size: Small
  - type: FlavorProfile
    flavors:
      - bluepumpkin
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 25
        reagents:
        - ReagentId: Ammonia
          Quantity: 10
        - ReagentId: Chlorine
          Quantity: 5
        - ReagentId: Vitamin
          Quantity: 10
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceBluePumpkin
        Quantity: 10
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/blue_pumpkin.rsi
  - type: Produce
    seedId: bluePumpkin
  - type: Damageable
    damageContainer: Biological
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 16
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: desecration
      - !type:SpillBehavior
        solution: food
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: pyrotton boll
  description: This will probably set you on fire.
  id: PyrottonBol
  parent: FoodProduceBase
  components:
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/pyrotton.rsi
  - type: FlavorProfile
    flavors:
      - pyrotton
  - type: Food
    requiresSpecialDigestion: true
  - type: SolutionContainerManager
    solutions:
      food:
        reagents:
        - ReagentId: Fiber
          Quantity: 5
        - ReagentId: Phlogiston
          Quantity: 5
  - type: Log
    spawnedPrototype: MaterialPyrotton1
    spawnCount: 2
  - type: Produce
    seedId: pyrotton
  - type: Tag
    tags:
    - ClothMade
    - CottonBoll
  - type: Extractable
    grindableSolutionName: food

- type: entity
  name: cherry
  parent: FoodProduceBase
  id: FoodCherry
  description: Juicy red cherry with a pit inside.
  components:
  - type: FlavorProfile
    flavors:
      - cherry
  - type: Food
    trash:
    - TrashCherryPit
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 8
        reagents:
        - ReagentId: Nutriment
          Quantity: 3
        - ReagentId: Vitamin
          Quantity: 3
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/cherry.rsi
  - type: Produce
    seedId: cherry
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceCherry
        Quantity: 5
  - type: Tag
    tags:
    - Fruit
  - type: FoodSequenceElement
    entries:
      Taco: Cherry
      Burger: Cherry

- type: entity
  name: cherry pit
  parent: FoodInjectableBase
  id: TrashCherryPit
  components:
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/cherry.rsi
    state: pit
  - type: Item
    sprite: Objects/Specific/Hydroponics/cherry.rsi
    heldPrefix: pit
  - type: Tag
    tags:
    - Recyclable
    - Trash
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 1
        reagents:
        - ReagentId: Toxin
          Quantity: 1
  - type: Extractable
    grindableSolutionName: food
  - type: Seed
    seedId: cherry
  - type: SpaceGarbage
  - type: BadFood

- type: entity
  name: anomaly berry
  description: A strange blue fruit. Something about it doesn't seem right.
  parent: FoodProduceBase
  id: FoodAnomalyBerry
  components:
  - type: FlavorProfile
    flavors:
      - strange
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/anomaly_berry.rsi
    state: produce
  - type: Produce
    seedId: anomalyBerry
  - type: Food
    trash:
    - EffectAnomalyFloraBulb # Random loot
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: Vitamin
          Quantity: 2
        - ReagentId: Artifexium
          Quantity: 1
  - type: Tag
    tags:
    - Fruit
  - type: FoodSequenceElement
    entries:
      Taco: AnomalyBerry
      Burger: AnomalyBerryBurger
