- type: entity
  name: pear
  parent: FoodProduceBase
  id: FoodPear
  description: it's peary good.
  components:
  - type: FlavorProfile
    flavors:
      - pear
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 15
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: Vitamin
          Quantity: 5
  - type: Sprite
    sprite: _NF/Objects/Specific/Hydroponics/pear.rsi
  - type: Produce
    seedId: pear
  - type: Tag
    tags:
      - Fruit

- type: entity
  name: coffee berries
  parent: FoodProduceBase
  id: FoodCoffee
  description: Red berries encasing coffee beans.
  components:
  - type: FlavorProfile
    flavors:
      - bitter
  - type: Food
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 12
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: Theobromine
          Quantity: 1
  - type: Sprite
    sprite: _NF/Objects/Specific/Hydroponics/coffee.rsi
  - type: Produce
    seedId: coffee
  - type: Tag
    tags:
    - Fruit
  - type: SpawnItemsOnUse
    items:
      - id: FoodCoffeeBeansRaw
    sound:
      path: /Audio/Effects/packetrip.ogg

- type: entity
  name: honeycomb
  parent: FoodProduceBase
  id: FoodHoneyComb
  description: Crispy container of honey.
  components:
  - type: FlavorProfile
    flavors:
      - honeycomb
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 20
        reagents:
        - ReagentId: Honey
          Quantity: 5
        - ReagentId: Vitamin
          Quantity: 5
  - type: Sprite
    sprite: _NF/Objects/Specific/Hydroponics/bees.rsi
    state: produce
  - type: Extractable
    grindableSolutionName: food
    juiceSolution:
      reagents:
      - ReagentId: Honey
        Quantity: 5
  - type: Tag
    tags:
      - Vegetable
