using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Floof.Bees;


[GenerateTypedNameReferences]
public sealed partial class ApiaryWindow : FancyWindow
{

    public event Action? OnBeeButton;
    public ApiaryWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        BeeButton.OnPressed += _ => OnBeeButton?.Invoke();
    }
}
